In [2]:
import numpy as np

In [3]:
mylist = [1,2,3]
x = np.array(mylist)
x

array([1, 2, 3])

In [4]:
y = np.array([4,5,6])
y




array([4, 5, 6])

In [5]:
m = np.array([[7,8,9],[10,11,12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [6]:
n = np.arange(0,30,2)
n



array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [8]:
n = n.reshape(3,5)
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [9]:
o = np.linspace(0,4,9)
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [10]:
o.resize(3,3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [12]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [15]:
np.array([1,2,3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [16]:
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [19]:
p = np.ones((2,3),int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [20]:
np.vstack([p,2*p])



array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [21]:
np.hstack([p,2*p])


array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

In [22]:
x + y

array([5, 7, 9])

In [23]:
x * y

array([ 4, 10, 18])

In [24]:
x ** 2

array([1, 4, 9])

In [25]:
x.dot(y)

32

In [26]:
z = np.array([y,y**2])
z



array([[ 4,  5,  6],
       [16, 25, 36]])

In [27]:
z.shape



(2, 3)

In [29]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [30]:
z.dtype



dtype('int64')

In [31]:
z = z.astype('f')
z.dtype

dtype('float32')

In [32]:
a = np.array([-4,-2,1,3,5])

In [33]:
a.sum()

3

In [34]:
a.max()

5

In [35]:
a.min()

-4

In [36]:
a.mean()

0.6

In [37]:
a.std()

3.2619012860600183

In [38]:
a.argmax()

4

In [39]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [40]:
s[0],s[4],s[:3]

(0, 16, array([0, 1, 4]))

In [41]:
s[-5::-2]

array([64, 36, 16,  4,  0])

In [50]:
r = np.arange(36)
r.resize((6,6))
r


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [51]:
r[2,2]

14

In [52]:
r[:2,:-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [53]:
r[r>30]

array([31, 32, 33, 34, 35])

In [54]:
r[-1,::2]

array([30, 32, 34])

In [55]:
r2 = r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [57]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [58]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [59]:
r_copy = r.copy()
r_copy


array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [60]:
test = np.random.randint(0,10,(4,3))
test

array([[3, 0, 6],
       [6, 5, 7],
       [8, 9, 1],
       [0, 5, 7]])

In [61]:
for row in test:
    print(row)

[3 0 6]
[6 5 7]
[8 9 1]
[0 5 7]


In [62]:
for i in range(len(test)):
    print(test[i])

[3 0 6]
[6 5 7]
[8 9 1]
[0 5 7]


In [64]:
for i,row in enumerate(test):
    print('row',i,'is',row)

row 0 is [3 0 6]
row 1 is [6 5 7]
row 2 is [8 9 1]
row 3 is [0 5 7]


In [65]:
test2 = test ** 2
test2

array([[ 9,  0, 36],
       [36, 25, 49],
       [64, 81,  1],
       [ 0, 25, 49]])

In [66]:
for i,j in zip(test, test2):
    print(i ,'+', j,'=',i+j)

[3 0 6] + [ 9  0 36] = [12  0 42]
[6 5 7] + [36 25 49] = [42 30 56]
[8 9 1] + [64 81  1] = [72 90  2]
[0 5 7] + [ 0 25 49] = [ 0 30 56]


In [67]:
y = lambda x:x+1


In [68]:
type(y)

function