In [1]:
import pandas as pd

In [2]:
import numpy as np

In [4]:
s1 = pd.Series([7.3,-2.5,3.4,1.5],index=['a','c','d','e'])
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [5]:
s2 = pd.Series([-2.1,3.6,-1.5,4,3.1],index=['a','c','e','f','g'])
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [6]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [7]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [8]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [9]:
df1 = pd.DataFrame(np.arange(9.).reshape((3,3)),
                  columns=list('bcd'),
                  index=['Ohio','Texas','Colorado'])
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [10]:
df2 = pd.DataFrame(np.arange(12.).reshape((4,3)),
                  columns=list('bde'),
                  index=['Utah','Ohio','Texas','Oregon'])
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [11]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [13]:
df1 = pd.DataFrame({'A':[1,2]})
df1

A
0  1
1  2

In [14]:
df2 = pd.DataFrame({'B':[3,4]})
df2

B
0  3
1  4

In [15]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

In [16]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)),
                  columns=list('abcd'))
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [18]:
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)),
                   columns=list('abcde'))
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [19]:
df2.loc[1,'b'] = np.nan

In [20]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [21]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [22]:
df1.add(df2,fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [23]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [24]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [26]:
df1.reindex(columns=df2.columns,fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [27]:
arr = np.arange(12.).reshape((3,4))

In [28]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [29]:
arr[0]

array([0., 1., 2., 3.])

In [30]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [31]:
frame = pd.DataFrame(np.arange(12.).reshape((4,3)),
                    columns=list('bde'),
                    index=['Utah','Ohio','Texas','Oregon'])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [32]:
series = frame.iloc[0]

In [33]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [34]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [36]:

series2 = pd.Series(range(3),index=list('bef'))
series2

b    0
e    1
f    2
dtype: int64

In [37]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [38]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [40]:
series3 = frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [41]:
frame.sub(series3,axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [42]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [43]:
frame = pd.DataFrame(np.random.randn(4,3),columns=list('bde'),
                    index=['Utah','Ohio','Texas','Oregon'])
frame

b         d         e
Utah    0.541535 -0.886949  0.371335
Ohio    0.036603 -0.154206  0.071503
Texas   0.539467  0.171323 -1.348202
Oregon  0.691435 -0.615809 -0.046611

In [44]:
np.abs(frame)

b         d         e
Utah    0.541535  0.886949  0.371335
Ohio    0.036603  0.154206  0.071503
Texas   0.539467  0.171323  1.348202
Oregon  0.691435  0.615809  0.046611

In [45]:
f = lambda x:x.max() - x.min()

In [48]:
frame.apply(f,axis=1)

Utah      1.428485
Ohio      0.225709
Texas     1.887669
Oregon    1.307244
dtype: float64

In [51]:
def f(x):
    return pd.Series([x.min(),x.max()],index=['min','max'])

In [52]:
frame.apply(f)

b         d         e
min  0.036603 -0.886949 -1.348202
max  0.691435  0.171323  0.371335

In [53]:
format = lambda x: '%.2f' % x

In [54]:
frame.applymap(format)

b      d      e
Utah    0.54  -0.89   0.37
Ohio    0.04  -0.15   0.07
Texas   0.54   0.17  -1.35
Oregon  0.69  -0.62  -0.05

In [56]:
frame['e'].map(formatmat)

Utah       0.37
Ohio       0.07
Texas     -1.35
Oregon    -0.05
Name: e, dtype: object

In [57]:
obj = pd.Series(range(4),index=['d','a','b','c'])

In [58]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [59]:
frame = pd.DataFrame(np.arange(8).reshape((2,4)),
                    index=['three','one'],
                    columns=['d','a','b','c'])
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [61]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [62]:
obj = pd.Series([4,7,-3,2])

In [63]:
obj

0    4
1    7
2   -3
3    2
dtype: int64

In [64]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [65]:
frame = pd.DataFrame({'b':[4,7,-3,2],
                     'a':[0,1,0,1]})

In [66]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [67]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [68]:
obj = pd.Series([7,-5,7,4,2,0,4])

In [69]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [70]:
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [72]:
obj = pd.Series(range(5),index=['a','a','b','b','c'])

In [73]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [74]:
obj.index.is_unique

False

In [75]:
obj['a']

a    0
a    1
dtype: int64

In [76]:
obj['c']

4

In [77]:
df = pd.DataFrame(np.random.randn(4,3),index=['a','a','b','b'])

In [78]:
df

0         1         2
a  0.072822 -0.911270 -2.117550
a  0.148046 -0.073120  0.927645
b  0.453427  0.757526  0.850227
b -0.819122 -1.136520  0.494911

In [79]:
df.loc['b']

0         1         2
b  0.453427  0.757526  0.850227
b -0.819122 -1.136520  0.494911

In [80]:
df.loc['a']

0        1         2
a  0.072822 -0.91127 -2.117550
a  0.148046 -0.07312  0.927645

In [82]:
df = pd.DataFrame([[1.4,np.nan],[7.1,-4.5],
                  [np.nan,np.nan],[0.75,-1.3]],
                 index=['a','b','c','d'],
                  columns=['one','two'])

In [83]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [84]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [86]:
df.sum(axis=0)

one    9.25
two   -5.80
dtype: float64

In [89]:
df.mean(axis='columns',skipna=True)

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [90]:
df.idxmax()

one    b
two    d
dtype: object

In [91]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [92]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [93]:
import pandas_datareader.data as web

ModuleNotFoundError: No module named 'pandas_datareader'

In [94]:
to_match = pd.Series(['c','a','b','b','c','a'])

In [95]:
unique_vals = pd.Series(['c','b','a'])

In [96]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2])